url: http://www.RNAintelligence.com
baseurl: /

# Site settings
title: RNA Intelligence
email: lulab1@tsinghua.edu.cn
description: "AI driven RNA therapy."


# Team names, titles and social links
people:
- name: Zhi John Lu
  pic: 1
  position: Lead Science
  social:
    - title: github
      url: http://github.com/lulab
    - title: facebook
      url: #
    - title: stack-overflow
      url: #


- name: Xiaofan Liu
  pic: 6
  position: Lead Bioinfo. & AI
  social:
    - title: github
      url: http://github.com/lulab
    - title: facebook
      url: #
    - title: stack-overflow
      url: #


- name: Hongli Ma
  pic: 4
  position: Lead Drug Design
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #



  

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url:
  - title: facebook
    url:
  - title: stack-overflow
    url:
  - title: bitbucket
    url:
  - title: github
    url: http://github.com/lulab

# Postal address (add as many lines as necessary)
address:
  - line: Biotech. Building
  - line: Tsinghua, Beijing 100084

# Build settings
markdown: kramdown
permalink: pretty
