##################
# ---- parameters for deploy prodcution
####must  run this option: JEKYLL_ENV=production bundle exec jekyll build --config _config2.yml 
##################
repository: lulab/AI
url: "http://lulab.life.tsinghua.edu.cn"
baseurl: /ai/


#########the following are the same ##########
# Site settings
title: RNA Intelligence
email: lulab1@tsinghua.edu.cn
description: "AI driven RNA therapy"


# Team names, titles and social links
people:
- name: Zhi John Lu
  pic: 2
  position: Lead Science
  social:
    - title: github
      url: http://github.com/lulab
    - title: facebook
      url: #
    - title: stack-overflow
      url: #


- name: Yucheng Yang
  pic: 3
  position: Lead Bioinformatics
  social:
    - title: github
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #


- name: Huiyi Li
  pic: 6
  position:  Lab Management
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #



  

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url:
  - title: facebook
    url:
  - title: stack-overflow
    url:
  - title: bitbucket
    url:
  - title: github
    url: http://github.com/lulab

# Postal address (add as many lines as necessary)
address:
  - line: Biotech. Building
  - line: Tsinghua, Beijing 100084

# Build settings
markdown: kramdown
permalink: pretty
